# Generated by Django 5.2.5 on 2025-09-11 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_descuento', models.DateField(blank=True, null=True)),
                ('tipo_descuento', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id_socio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('id_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaApp.pagos')),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='descuentos_fotos/')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaApp.proveedores')),
            ],
        ),
        migrations.AddField(
            model_name='pagos',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaApp.socios'),
        ),
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id_credencial', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('id_socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistemaApp.socios')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwd', models.CharField(max_length=128)),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaApp.proveedores')),
                ('id_socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistemaApp.socios')),
            ],
        ),
    ]
