# Generated by Django 5.2.5 on 2025-09-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credenciales',
            table='credenciales',
        ),
        migrations.AlterModelTable(
            name='cuotas',
            table='cuotas',
        ),
        migrations.AlterModelTable(
            name='descuentos',
            table='descuentos',
        ),
        migrations.AlterModelTable(
            name='pagos',
            table='pagos',
        ),
        migrations.AlterModelTable(
            name='proveedores',
            table='proveedores',
        ),
        migrations.AlterModelTable(
            name='socios',
            table='socios',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
