# Generated by Django 5.2.5 on 2025-10-07 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0002_alter_credenciales_table_alter_cuotas_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_socio',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaApp.usuarios'),
        ),
        migrations.AddField(
            model_name='socios',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaApp.usuarios'),
        ),
    ]
