# Generated by Django 5.2.5 on 2025-10-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0003_remove_usuarios_id_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
