# Generated by Django 5.2.5 on 2025-10-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0004_proveedores_apellido_socios_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('normal', 'Usuario')], default='admin', max_length=10),
        ),
    ]
