# Generated by Django 5.2.5 on 2025-11-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0006_proveedores_email_proveedores_passwd_socios_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIngreso',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('socio', 'Socio'), ('proveedor', 'Proveedor')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solicitudes_ingreso',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='tipo_usuario',
        ),
    ]
